from weightlab.corpus import prepare_repository_corpus


def test_repository_corpus_filters_license_generated_secrets_and_duplicates(tmp_path):
    repo = tmp_path / "repo_a"
    repo.mkdir()
    (repo / "LICENSE").write_text("MIT License\n", encoding="utf-8")
    (repo / "src").mkdir()
    (repo / "src" / "main.py").write_text(
        "def parse_config(text):\n"
        "    \"\"\"Parse config text.\"\"\"\n"
        "    return text.strip()\n",
        encoding="utf-8",
    )
    (repo / "README.md").write_text("# Repo A\nUse parse_config.\n", encoding="utf-8")
    (repo / "COPY.md").write_text("# Repo A\nUse parse_config.\n", encoding="utf-8")
    (repo / "generated.py").write_text("# Generated by tool\nVALUE = 1\n", encoding="utf-8")
    (repo / "secret.py").write_text(
        "TOKEN = 'ghp_abcdefghijklmnopqrstuvwxyz1234567890'\n",
        encoding="utf-8",
    )

    result = prepare_repository_corpus([repo], min_tokens=1)

    included_paths = {doc["relative_path"] for doc in result["documents"]}
    excluded_reasons = {
        row["relative_path"]: row["reason"] for row in result["excluded_documents"]
    }
    assert result["status"] == "completed"
    assert result["repo_count"] == 1
    assert result["license_counts"]["MIT"] == 1
    assert "src/main.py" in included_paths
    assert "README.md" in included_paths
    assert excluded_reasons["COPY.md"] == "duplicate_content"
    assert excluded_reasons["generated.py"] == "generated_file"
    assert excluded_reasons["secret.py"] == "secret_pattern"
    assert result["total_tokens"] >= 1
    assert result["split_counts"]["train"] == len(result["documents"])
    assert result["languages"]["Python"] >= 1
    assert result["file_roles"]["code"] >= 1
    assert result["file_roles"]["readme"] >= 1


def test_repository_corpus_rejects_unknown_license(tmp_path):
    repo = tmp_path / "repo_b"
    repo.mkdir()
    (repo / "LICENSE").write_text("All rights reserved.\n", encoding="utf-8")
    (repo / "main.py").write_text("print('nope')\n", encoding="utf-8")

    result = prepare_repository_corpus([repo], min_tokens=1)

    assert result["status"] == "insufficient_tokens"
    assert result["repo_count"] == 0
    assert result["total_tokens"] == 0
    assert result["rejected_repositories"][0]["reason"] == "unsupported_license"
