from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any
from urllib.parse import urlencode
from urllib.request import urlopen

DATASETS_SERVER = "https://datasets-server.huggingface.co"
HUGGINGFACE_API = "https://huggingface.co/api"

KNOWN_LICENSES = {
    "agpl-3.0",
    "apache-2.0",
    "artistic-2.0",
    "bsd-2-clause",
    "bsd-3-clause",
    "cc0-1.0",
    "epl-1.0",
    "gpl-2.0",
    "gpl-3.0",
    "isc",
    "lgpl-2.1",
    "lgpl-3.0",
    "mit",
    "mpl-2.0",
    "unlicense",
}

DEFAULT_FILTER_POLICY = {
    "corpus_use": "exploratory-research-only",
    "production_approval": False,
    "redistribution_approval": False,
    "license_metadata_policy": (
        "record stated license/config metadata and restrictions; do not reject normally "
        "accessible rows solely for mixed, other, unknown, gated, or unsuitable-for-production "
        "license metadata during this exploratory phase"
    ),
    "strict_policy_deferred": (
        "later production/company deployment pass must apply strict legal and company-policy "
        "filters before any redistribution or deployment"
    ),
    "secret_scan": [
        "api_key",
        "aws_access_key_id",
        "bearer ",
        "client_secret",
        "private_key",
        "secret",
        "token",
    ],
    "path_excludes": [
        ".git/",
        "__pycache__/",
        "build/",
        "dist/",
        "node_modules/",
        "site-packages/",
        "third_party/",
        "vendor/",
    ],
    "generated_file_markers": [
        "auto-generated",
        "autogenerated",
        "do not edit",
        "generated by",
    ],
    "binary_rejection": "reject rows containing NUL bytes or decode failures",
    "deduplication": {
        "exact": "sha256 over normalized text",
        "near": "simhash/minhash before materialized train/validation split",
    },
    "split_policy": "repository-aware hash split by repo name before file-level shuffling",
}

DATASET_COLUMN_ALIASES = {
    "text": ["code", "code_text", "content", "text"],
    "repo": ["repo_name", "repository_name", "repo", "repository"],
    "path": ["path", "file_path", "filepath", "file"],
    "license": ["license"],
    "language": ["language", "lang"],
    "size": ["size", "bytes"],
}


@dataclass(frozen=True)
class HFSourceSpec:
    dataset: str
    revision: str
    configs: list[str]
    split: str = "train"
    card_review: str = ""
    local_mirror_dir: str = "data/hf_mirror"


def build_hf_corpus_manifest(
    sources: list[HFSourceSpec],
    *,
    fetch_json: Callable[[str], dict[str, Any]] | None = None,
) -> dict[str, Any]:
    fetch = fetch_json or _fetch_json
    manifest_sources = [_build_source_manifest(source, fetch) for source in sources]
    accepted_config_count = sum(len(source["accepted_configs"]) for source in manifest_sources)
    rejected_config_count = sum(len(source["rejected_configs"]) for source in manifest_sources)
    total_rows = sum(
        int(config["num_rows"])
        for source in manifest_sources
        for config in source["accepted_configs"]
    )
    total_parquet_bytes = sum(
        int(config["parquet_bytes"])
        for source in manifest_sources
        for config in source["accepted_configs"]
    )
    checksum_payload = {
        "sources": [
            {
                "dataset": source["dataset"],
                "revision": source["resolved_revision"],
                "accepted_configs": [
                    {
                        "config": config["config"],
                        "split": config["split"],
                        "parquet_files": [
                            {
                                "url": parquet["url"],
                                "size": parquet["size"],
                            }
                            for parquet in config["parquet_files"]
                        ],
                    }
                    for config in source["accepted_configs"]
                ],
            }
            for source in manifest_sources
        ]
    }
    manifest_sha256 = hashlib.sha256(
        json.dumps(checksum_payload, sort_keys=True).encode("utf-8")
    ).hexdigest()
    return {
        "benchmark_label": "hf_corpus_manifest",
        "status": "completed" if accepted_config_count else "failed",
        "source_count": len(manifest_sources),
        "accepted_config_count": accepted_config_count,
        "rejected_config_count": rejected_config_count,
        "total_rows": total_rows,
        "total_parquet_bytes": total_parquet_bytes,
        "token_count": {
            "status": "not_materialized_yet",
            "method": "will count byte-tokenizer tokens during streamed mirror build",
            "count": 0,
            "target_min_tokens": 50_000_000,
        },
        "sources": manifest_sources,
        "filter_policy": DEFAULT_FILTER_POLICY,
        "datasets_loader_policy": {
            "library": "datasets",
            "dataset_builder": "parquet",
            "streaming": True,
            "trust_remote_code": False,
            "pin_revision": True,
            "cache_dir": "data/hf_cache",
            "local_mirror_dir": "data/hf_mirror",
            "load_dataset_template": (
                "load_dataset('parquet', data_files={'train': parquet_urls}, "
                "split='train', streaming=True, cache_dir='data/hf_cache')"
            ),
            "remote_dataset_script_policy": (
                "do not execute dataset repository scripts; use Dataset Viewer "
                "converted parquet URLs pinned by dataset revision metadata"
            ),
        },
        "manifest_sha256": manifest_sha256,
        "limitations": [
            "metadata_manifest_only",
            "parquet_shards_not_downloaded_yet",
            "token_count_pending_materialized_stream",
            "row_level_vendor_secret_quality_filters_pending_streaming_pass",
            "exploratory_research_only_not_production_approved",
        ],
    }


def _build_source_manifest(
    source: HFSourceSpec,
    fetch_json: Callable[[str], dict[str, Any]],
) -> dict[str, Any]:
    repo = fetch_json(f"{HUGGINGFACE_API}/datasets/{source.dataset}")
    resolved_revision = str(repo.get("sha") or source.revision)
    if source.revision and resolved_revision != source.revision:
        raise ValueError(
            f"{source.dataset} resolved revision {resolved_revision} does not match "
            f"pinned revision {source.revision}"
        )

    size_payload = fetch_json(_dataset_viewer_url("size", source.dataset))
    parquet_payload = fetch_json(_dataset_viewer_url("parquet", source.dataset))
    size_rows = _index_size_rows(size_payload)
    parquet_rows = _index_parquet_rows(parquet_payload)

    accepted_configs: list[dict[str, Any]] = []
    rejected_configs: list[dict[str, Any]] = []
    for config in source.configs:
        license_name = config_license(config)
        key = (config, source.split)
        size_row = size_rows.get(key, {})
        parquet_files = parquet_rows.get(key, [])
        if not parquet_files:
            rejected_configs.append(
                {
                    "config": config,
                    "split": source.split,
                    "license": license_name,
                    "reason": "missing_dataset_viewer_parquet_metadata",
                }
            )
            continue
        accepted_configs.append(
            {
                "config": config,
                "split": source.split,
                "language": config_language(config),
                "license": license_name,
                "license_metadata_status": license_metadata_status(license_name),
                "corpus_use": "exploratory-research-only",
                "num_rows": int(size_row.get("num_rows") or 0),
                "parquet_bytes": int(
                    size_row.get("num_bytes_parquet_files")
                    or sum(int(row.get("size") or 0) for row in parquet_files)
                ),
                "memory_bytes": int(size_row.get("num_bytes_memory") or 0),
                "parquet_files": [
                    {
                        "filename": str(row.get("filename", "")),
                        "url": str(row.get("url", "")),
                        "size": int(row.get("size") or 0),
                        "sha256": "metadata_only_not_downloaded",
                    }
                    for row in parquet_files
                ],
            }
        )

    return {
        "dataset": source.dataset,
        "requested_revision": source.revision,
        "resolved_revision": resolved_revision,
        "last_modified": repo.get("lastModified", ""),
        "card_license": _card_license(repo),
        "restrictions": repo.get("gated", False),
        "tags": [tag for tag in repo.get("tags", []) if str(tag).startswith("license:")],
        "card_review": source.card_review,
        "accepted_configs": accepted_configs,
        "rejected_configs": rejected_configs,
        "column_aliases": DATASET_COLUMN_ALIASES,
        "local_mirror_dir": f"{source.local_mirror_dir}/{source.dataset.replace('/', '__')}",
    }


def config_language(config: str) -> str:
    if "-" not in config:
        return config
    if config.lower().endswith("-all"):
        return config[:-4]
    return config.rsplit(f"-{config_license(config)}", maxsplit=1)[0]


def config_license(config: str) -> str:
    lowered = config.lower()
    for license_name in sorted(KNOWN_LICENSES, key=len, reverse=True):
        suffix = f"-{license_name}"
        if lowered.endswith(suffix):
            return license_name
    if lowered.endswith("-all"):
        return "mixed"
    return "unknown"


def license_metadata_status(license_name: str) -> str:
    if license_name in {"mixed", "other", "unknown"}:
        return "recorded_mixed_or_unclear_exploratory_only"
    return "recorded_exploratory_only"


def _card_license(repo: dict[str, Any]) -> str:
    card_data = repo.get("cardData") or {}
    license_value = card_data.get("license")
    if isinstance(license_value, list):
        return ",".join(str(item) for item in license_value)
    if license_value:
        return str(license_value)
    for tag in repo.get("tags", []):
        text = str(tag)
        if text.startswith("license:"):
            return text.removeprefix("license:")
    return "unknown"


def _index_size_rows(payload: dict[str, Any]) -> dict[tuple[str, str], dict[str, Any]]:
    size = payload.get("size") or {}
    rows = list(size.get("splits") or [])
    if not rows:
        rows = [
            dict(config_row, split="train")
            for config_row in size.get("configs", [])
            if "config" in config_row
        ]
    return {
        (str(row.get("config", "")), str(row.get("split", "train"))): row
        for row in rows
    }


def _index_parquet_rows(payload: dict[str, Any]) -> dict[tuple[str, str], list[dict[str, Any]]]:
    indexed: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in payload.get("parquet_files", []):
        key = (str(row.get("config", "")), str(row.get("split", "train")))
        indexed.setdefault(key, []).append(row)
    return indexed


def _dataset_viewer_url(endpoint: str, dataset: str) -> str:
    return f"{DATASETS_SERVER}/{endpoint}?{urlencode({'dataset': dataset}, safe='/')}"


def _fetch_json(url: str) -> dict[str, Any]:
    with urlopen(url, timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))
