from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from weightlab.hf_corpus import DATASET_COLUMN_ALIASES

TIMESTAMP_COLUMN_ALIASES = [
    "commit_date",
    "committed_date",
    "created_at",
    "date",
    "last_modified",
    "modified_at",
    "pushed_at",
    "updated_at",
]

SECRET_PATTERNS = [
    re.compile(r"ghp_[A-Za-z0-9_]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (?:RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][^'\"]{12,}['\"]"),
    re.compile(r"(?i)authorization:\s*bearer\s+[A-Za-z0-9._\-]{16,}"),
]

PATH_EXCLUDES = (
    ".git/",
    "__pycache__/",
    "build/",
    "dist/",
    "node_modules/",
    "site-packages/",
    "third_party/",
    "vendor/",
)

GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated by",
    "this file was generated",
)

MALICIOUS_INSTRUCTION_MARKERS = (
    "ignore previous instructions",
    "ignore all previous instructions",
    "reveal your system prompt",
    "developer message",
    "system prompt",
    "prompt injection",
)

CONTAMINATION_PATH_MARKERS = (
    "/benchmark/",
    "/benchmarks/",
    "/eval/",
    "/evals/",
    "/evaluation/",
    "/evaluations/",
    "humaneval",
    "mbpp",
)

TEST_PATH_MARKERS = (
    "/test/",
    "/tests/",
    "/spec/",
    "/specs/",
    "__tests__/",
)

TEST_FILE_PATTERNS = (
    ".test.",
    ".spec.",
    "_test.",
    "_spec.",
)

DOCUMENTATION_PATH_MARKERS = (
    "/doc/",
    "/docs/",
    "/documentation/",
)

README_NAMES = (
    "readme",
    "readme.md",
    "readme.rst",
    "readme.txt",
)

CHANGELOG_NAMES = (
    "changelog",
    "changelog.md",
    "changes.md",
    "history.md",
    "release-notes.md",
    "releasenotes.md",
)

DOCSTRING_PATTERNS = (
    re.compile(r'(?s)"""[^"]{12,}"""'),
    re.compile(r"(?s)'''[^']{12,}'''"),
    re.compile(r"(?s)/\*\*.*?\*/"),
)


@dataclass(frozen=True)
class MaterializationConfig:
    target_train_tokens: int = 50_000_000
    max_train_tokens_per_config: int | None = None
    max_row_bytes: int = 256_000
    min_row_bytes: int = 20
    max_rows: int | None = None
    corpus_use: str = "exploratory-research-only"
    near_duplicate_hamming_threshold: int | None = 3
    near_duplicate_min_bytes: int = 200


RowFactory = Callable[[dict[str, Any], dict[str, Any]], Iterable[dict[str, Any]]]


def materialize_hf_corpus(
    hf_manifest_record: dict[str, Any],
    *,
    output_jsonl: Path,
    row_factory: RowFactory,
    config: MaterializationConfig | None = None,
    resume: bool = True,
) -> dict[str, Any]:
    config = config or MaterializationConfig()
    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    seen_hashes: set[str] = set()
    near_duplicate_index: dict[int, list[int]] = {}
    existing_metrics = (
        _load_existing_rows(output_jsonl, seen_hashes, near_duplicate_index, config)
        if resume
        else _empty_metrics()
    )
    mode = "a" if resume and output_jsonl.exists() else "w"

    source_manifest_metrics = hf_manifest_record["metrics"]
    dataset_revisions = {
        source["dataset"]: source["resolved_revision"]
        for source in source_manifest_metrics["sources"]
    }
    counters = _Counters.from_existing(existing_metrics)
    excluded_examples: list[dict[str, str]] = []

    with output_jsonl.open(mode, encoding="utf-8") as handle:
        for source in source_manifest_metrics["sources"]:
            for accepted_config in source["accepted_configs"]:
                if _target_met(counters, config):
                    break
                config_key = _config_key(source, accepted_config)
                if _config_train_cap_met(counters, config, config_key):
                    continue
                rows = row_factory(source, accepted_config)
                for raw_row in rows:
                    if _target_met(counters, config):
                        break
                    if _config_train_cap_met(counters, config, config_key):
                        break
                    counters.rows_seen += 1
                    candidate = _row_to_candidate(
                        source,
                        accepted_config,
                        raw_row,
                        corpus_use=config.corpus_use,
                    )
                    reason = _rejection_reason(
                        candidate,
                        seen_hashes,
                        near_duplicate_index,
                        config,
                    )
                    if reason:
                        counters.excluded_reasons[reason] += 1
                        if len(excluded_examples) < 50:
                            excluded_examples.append(
                                {
                                    "dataset": candidate["dataset"],
                                    "config": candidate["config"],
                                    "repo": candidate["repo"],
                                    "path": candidate["path"],
                                    "reason": reason,
                                }
                            )
                        continue
                    seen_hashes.add(candidate["text_sha256"])
                    _add_near_duplicate_hash(candidate, near_duplicate_index, config)
                    handle.write(json.dumps(candidate, sort_keys=True) + "\n")
                    counters.accept(candidate)
                if _target_met(counters, config):
                    break

    checksum = _file_sha256(output_jsonl)
    status = (
        "completed"
        if counters.split_tokens["train"] >= config.target_train_tokens
        else "insufficient_tokens"
    )
    return {
        "benchmark_label": "hf_corpus_materialization",
        "status": status,
        "corpus_use": config.corpus_use,
        "production_approval": False,
        "redistribution_approval": False,
        "source_manifest": {
            "experiment_id": hf_manifest_record["experiment_id"],
            "git_commit": hf_manifest_record["git_commit"],
            "manifest_sha256": source_manifest_metrics["manifest_sha256"],
            "dataset_revisions": dataset_revisions,
        },
        "output": {
            "jsonl_path": str(output_jsonl),
            "bytes": output_jsonl.stat().st_size if output_jsonl.exists() else 0,
            "sha256": checksum,
        },
        "target_train_tokens": config.target_train_tokens,
        "max_train_tokens_per_config": config.max_train_tokens_per_config,
        "meets_50m_token_requirement": counters.split_tokens["train"] >= 50_000_000,
        "rows_seen": counters.rows_seen,
        "rows_accepted": counters.rows_accepted,
        "rows_excluded": sum(counters.excluded_reasons.values()),
        "excluded_reasons": dict(sorted(counters.excluded_reasons.items())),
        "excluded_examples": excluded_examples,
        "tokens": dict(sorted(counters.split_tokens.items())),
        "total_tokens": sum(counters.split_tokens.values()),
        "document_count": counters.rows_accepted,
        "split_counts": dict(sorted(counters.split_counts.items())),
        "config_split_tokens": dict(sorted(counters.config_split_tokens.items())),
        "temporal_split_counts": dict(sorted(counters.temporal_split_counts.items())),
        "temporal_split_tokens": dict(sorted(counters.temporal_split_tokens.items())),
        "content_role_counts": dict(sorted(counters.content_role_counts.items())),
        "content_role_tokens": dict(sorted(counters.content_role_tokens.items())),
        "timestamp_coverage": {
            "rows_with_timestamp": counters.rows_with_timestamp,
            "rows_without_timestamp": counters.rows_without_timestamp,
            "coverage_ratio": _ratio(counters.rows_with_timestamp, counters.rows_accepted),
        },
        "dataset_config_counts": dict(sorted(counters.dataset_config_counts.items())),
        "languages": dict(sorted(counters.languages.items())),
        "licenses": dict(sorted(counters.licenses.items())),
        "transformations": [
            "extract text/repo/path/language/license columns from Dataset Viewer parquet rows",
            "reject binary/corrupt/unusable rows",
            "reject technical secret/confidential patterns",
            "reject generated/vendor dependency paths",
            "reject exact duplicate normalized text",
            "reject near-duplicate normalized text by deterministic simhash bands",
            "reject known evaluation-contamination path markers",
            "reject malicious embedded instruction markers",
            "assign repository-aware train/validation/test split by stable repo hash",
            "record independent temporal split labels when row timestamp columns exist",
            "classify each row as source/test/readme/documentation/docstring/changelog content",
            "count byte-tokenizer tokens as utf8 bytes plus eos",
            "optionally cap accepted train tokens per dataset/config before moving on",
            "write jsonl rows with source dataset/config/revision and row checksums",
        ],
        "filters": {
            "max_row_bytes": config.max_row_bytes,
            "min_row_bytes": config.min_row_bytes,
            "path_excludes": list(PATH_EXCLUDES),
            "contamination_path_markers": list(CONTAMINATION_PATH_MARKERS),
            "generated_markers": list(GENERATED_MARKERS),
            "malicious_instruction_markers": list(MALICIOUS_INSTRUCTION_MARKERS),
            "near_duplicate": {
                "algorithm": "simhash64_over_normalized_token_shingles",
                "hamming_threshold": config.near_duplicate_hamming_threshold,
                "min_bytes": config.near_duplicate_min_bytes,
                "bands": "4x16-bit exact band lookup before hamming confirmation",
            },
            "temporal_split": {
                "timestamp_columns": TIMESTAMP_COLUMN_ALIASES,
                "test": "year >= 2023",
                "validation": "year >= 2022 and year < 2023",
                "train": "year < 2022",
                "unknown": "timestamp missing or unparseable",
            },
            "content_roles": {
                "test": "test/spec paths or filenames",
                "readme": "README-style basenames",
                "documentation": (
                    "docs/documentation paths, README files, changelogs, "
                    "or markdown/rst docs"
                ),
                "docstring": "Python triple-quoted or JSDoc-style documentation blocks",
                "changelog": "changelog/changes/history/release-notes basenames",
                "source": (
                    "default role when no specialized non-source role is detected, "
                    "or when source code also contains docstrings"
                ),
            },
        },
        "limitations": [
            "exploratory_research_only_not_production_approved",
            "mixed_or_unclear_license_metadata_not_blocking_exploratory_training",
            "near_duplicate_filter_is_simhash_heuristic_not_full_minhash_lsh",
            "primary_training_split_remains_repository_hash_split",
            "temporal_split_depends_on_source_timestamp_column_coverage",
            "no_functional_training_run_from_this_mirror_yet",
        ],
    }


def load_jsonl_texts(
    path: Path,
    max_documents: int | None = None,
    *,
    split: str | None = None,
) -> list[str]:
    texts: list[str] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            if split is not None and row.get("split") != split:
                continue
            texts.append(str(row["text"]))
            if max_documents is not None and len(texts) >= max_documents:
                break
    return texts


@dataclass
class _Counters:
    rows_seen: int
    rows_accepted: int
    split_tokens: Counter[str]
    split_counts: Counter[str]
    dataset_config_counts: Counter[str]
    config_split_tokens: Counter[str]
    temporal_split_counts: Counter[str]
    temporal_split_tokens: Counter[str]
    content_role_counts: Counter[str]
    content_role_tokens: Counter[str]
    languages: Counter[str]
    licenses: Counter[str]
    excluded_reasons: Counter[str]
    rows_with_timestamp: int
    rows_without_timestamp: int

    @classmethod
    def from_existing(cls, metrics: dict[str, Any]) -> _Counters:
        return cls(
            rows_seen=int(metrics.get("rows_seen", 0)),
            rows_accepted=int(metrics.get("rows_accepted", 0)),
            split_tokens=Counter(metrics.get("tokens", {})),
            split_counts=Counter(metrics.get("split_counts", {})),
            dataset_config_counts=Counter(metrics.get("dataset_config_counts", {})),
            config_split_tokens=Counter(metrics.get("config_split_tokens", {})),
            temporal_split_counts=Counter(metrics.get("temporal_split_counts", {})),
            temporal_split_tokens=Counter(metrics.get("temporal_split_tokens", {})),
            content_role_counts=Counter(metrics.get("content_role_counts", {})),
            content_role_tokens=Counter(metrics.get("content_role_tokens", {})),
            languages=Counter(metrics.get("languages", {})),
            licenses=Counter(metrics.get("licenses", {})),
            excluded_reasons=Counter(metrics.get("excluded_reasons", {})),
            rows_with_timestamp=int(
                metrics.get("timestamp_coverage", {}).get("rows_with_timestamp", 0)
            ),
            rows_without_timestamp=int(
                metrics.get("timestamp_coverage", {}).get("rows_without_timestamp", 0)
            ),
        )

    def accept(self, row: dict[str, Any]) -> None:
        split = str(row["split"])
        temporal_split = str(row.get("temporal_split", "unknown"))
        self.rows_accepted += 1
        self.split_tokens[split] += int(row["tokens"])
        self.split_counts[split] += 1
        config_key = f"{row['dataset']}::{row['config']}"
        self.dataset_config_counts[config_key] += 1
        self.config_split_tokens[f"{config_key}::{split}"] += int(row["tokens"])
        self.temporal_split_counts[temporal_split] += 1
        self.temporal_split_tokens[temporal_split] += int(row["tokens"])
        for role in row.get("content_roles", ["source"]):
            self.content_role_counts[str(role)] += 1
            self.content_role_tokens[str(role)] += int(row["tokens"])
        if row.get("source_timestamp"):
            self.rows_with_timestamp += 1
        else:
            self.rows_without_timestamp += 1
        self.languages[str(row["language"])] += 1
        self.licenses[str(row["license"])] += 1


def _row_to_candidate(
    source: dict[str, Any],
    accepted_config: dict[str, Any],
    raw_row: dict[str, Any],
    *,
    corpus_use: str,
) -> dict[str, Any]:
    text = _first_value(raw_row, DATASET_COLUMN_ALIASES["text"])
    repo = _first_value(raw_row, DATASET_COLUMN_ALIASES["repo"])
    path = _first_value(raw_row, DATASET_COLUMN_ALIASES["path"])
    language = _first_value(raw_row, DATASET_COLUMN_ALIASES["language"]) or accepted_config[
        "language"
    ]
    license_name = _first_value(raw_row, DATASET_COLUMN_ALIASES["license"]) or accepted_config[
        "license"
    ]
    normalized = _normalize_text(text)
    text_sha256 = hashlib.sha256(normalized.encode("utf-8", errors="ignore")).hexdigest()
    repo_split = _repo_split(repo)
    source_timestamp = _first_value(raw_row, TIMESTAMP_COLUMN_ALIASES)
    temporal_split = _temporal_split(source_timestamp)
    simhash64 = _simhash64(normalized)
    content_roles = _content_roles(path, text, language)
    return {
        "dataset": source["dataset"],
        "config": accepted_config["config"],
        "dataset_revision": source["resolved_revision"],
        "source_manifest_sha256": source.get("manifest_sha256", ""),
        "split": repo_split,
        "repo_split": repo_split,
        "temporal_split": temporal_split,
        "source_timestamp": source_timestamp,
        "repo": repo,
        "path": path,
        "language": language,
        "license": license_name,
        "license_metadata_status": accepted_config.get("license_metadata_status", ""),
        "corpus_use": corpus_use,
        "content_roles": content_roles,
        "text": text,
        "tokens": _byte_tokens(text),
        "bytes": len(text.encode("utf-8", errors="ignore")),
        "text_sha256": text_sha256,
        "near_duplicate_simhash64": f"{simhash64:016x}",
        "row_sha256": hashlib.sha256(
            json.dumps(
                {
                    "dataset": source["dataset"],
                    "config": accepted_config["config"],
                    "repo": repo,
                    "path": path,
                    "text_sha256": text_sha256,
                },
                sort_keys=True,
            ).encode("utf-8")
        ).hexdigest(),
    }


def _rejection_reason(
    row: dict[str, Any],
    seen_hashes: set[str],
    near_duplicate_index: dict[int, list[int]],
    config: MaterializationConfig,
) -> str:
    text = row["text"]
    path = f"/{str(row['path']).lower()}"
    lowered_text_head = text[:4096].lower()
    if not text or not str(text).strip():
        return "empty_text"
    if len(text.encode("utf-8", errors="ignore")) < config.min_row_bytes:
        return "too_small"
    if row["bytes"] > config.max_row_bytes:
        return "too_large"
    if "\x00" in text:
        return "binary_or_corrupt"
    if row["text_sha256"] in seen_hashes:
        return "duplicate_text"
    if _is_near_duplicate(row, near_duplicate_index, config):
        return "near_duplicate_text"
    if any(marker in path for marker in PATH_EXCLUDES) or path.endswith(".min.js"):
        return "vendor_or_generated_path"
    if any(marker in path for marker in CONTAMINATION_PATH_MARKERS):
        return "evaluation_contamination_path"
    if any(marker in lowered_text_head for marker in GENERATED_MARKERS):
        return "generated_marker"
    if any(pattern.search(text) for pattern in SECRET_PATTERNS):
        return "secret_or_confidential_pattern"
    if any(marker in lowered_text_head for marker in MALICIOUS_INSTRUCTION_MARKERS):
        return "malicious_embedded_instruction"
    return ""


def _target_met(counters: _Counters, config: MaterializationConfig) -> bool:
    if counters.split_tokens["train"] >= config.target_train_tokens:
        return True
    return config.max_rows is not None and counters.rows_accepted >= config.max_rows


def _config_train_cap_met(
    counters: _Counters,
    config: MaterializationConfig,
    config_key: str,
) -> bool:
    if config.max_train_tokens_per_config is None:
        return False
    return (
        counters.config_split_tokens[f"{config_key}::train"]
        >= config.max_train_tokens_per_config
    )


def _config_key(source: dict[str, Any], accepted_config: dict[str, Any]) -> str:
    return f"{source['dataset']}::{accepted_config['config']}"


def _first_value(row: dict[str, Any], names: list[str]) -> str:
    for name in names:
        value = row.get(name)
        if value is not None:
            return str(value)
    return ""


def _normalize_text(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.strip().splitlines())


def _byte_tokens(text: str) -> int:
    return len(text.encode("utf-8", errors="ignore")) + 1


def _content_roles(path: str, text: str, language: str) -> list[str]:
    normalized_path = str(path).replace("\\", "/").lower()
    basename = normalized_path.rsplit("/", maxsplit=1)[-1]
    roles: list[str] = []
    if (
        any(marker in f"/{normalized_path}" for marker in TEST_PATH_MARKERS)
        or any(pattern in basename for pattern in TEST_FILE_PATTERNS)
    ):
        roles.append("test")
    if basename in README_NAMES or basename.startswith("readme."):
        roles.append("readme")
    if basename in CHANGELOG_NAMES or basename.startswith(("changelog.", "changes.")):
        roles.append("changelog")
    if (
        any(marker in f"/{normalized_path}" for marker in DOCUMENTATION_PATH_MARKERS)
        or "readme" in roles
        or "changelog" in roles
        or basename.endswith((".md", ".rst", ".adoc"))
    ):
        roles.append("documentation")
    has_docstring = _has_docstring(text)
    if has_docstring:
        roles.append("docstring")
    non_source_roles = {"test", "readme", "documentation", "changelog"}
    if has_docstring or not any(role in non_source_roles for role in roles):
        roles.append("source")
    return roles


def _has_docstring(text: str) -> bool:
    head = text[:8192]
    return any(pattern.search(head) for pattern in DOCSTRING_PATTERNS)


def _temporal_split(timestamp: str) -> str:
    year = _timestamp_year(timestamp)
    if year is None:
        return "unknown"
    if year >= 2023:
        return "test"
    if year >= 2022:
        return "validation"
    return "train"


def _timestamp_year(timestamp: str) -> int | None:
    match = re.search(r"(?<!\d)(19\d{2}|20\d{2})(?!\d)", str(timestamp))
    return int(match.group(1)) if match else None


def _repo_split(repo: str) -> str:
    digest = hashlib.sha256(repo.encode("utf-8", errors="ignore")).digest()
    bucket = int.from_bytes(digest[:2], "big") % 100
    if bucket < 2:
        return "test"
    if bucket < 5:
        return "validation"
    return "train"


def _simhash64(text: str) -> int:
    tokens = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\s]", text.lower())
    if not tokens:
        return 0
    shingle_size = 5 if len(tokens) >= 5 else len(tokens)
    features = [
        " ".join(tokens[index : index + shingle_size])
        for index in range(0, len(tokens) - shingle_size + 1)
    ]
    vector = [0] * 64
    for feature in features:
        digest = hashlib.blake2b(feature.encode("utf-8"), digest_size=8).digest()
        value = int.from_bytes(digest, "big")
        for bit in range(64):
            vector[bit] += 1 if value & (1 << bit) else -1
    simhash = 0
    for bit, score in enumerate(vector):
        if score >= 0:
            simhash |= 1 << bit
    return simhash


def _is_near_duplicate(
    row: dict[str, Any],
    near_duplicate_index: dict[int, list[int]],
    config: MaterializationConfig,
) -> bool:
    if config.near_duplicate_hamming_threshold is None:
        return False
    if int(row["bytes"]) < config.near_duplicate_min_bytes:
        return False
    simhash = int(str(row["near_duplicate_simhash64"]), 16)
    candidates: set[int] = set()
    for band in _simhash_bands(simhash):
        candidates.update(near_duplicate_index.get(band, []))
    return any(
        (simhash ^ previous).bit_count() <= config.near_duplicate_hamming_threshold
        for previous in candidates
    )


def _add_near_duplicate_hash(
    row: dict[str, Any],
    near_duplicate_index: dict[int, list[int]],
    config: MaterializationConfig,
) -> None:
    if config.near_duplicate_hamming_threshold is None:
        return
    if int(row["bytes"]) < config.near_duplicate_min_bytes:
        return
    simhash = int(str(row["near_duplicate_simhash64"]), 16)
    for band in _simhash_bands(simhash):
        near_duplicate_index.setdefault(band, []).append(simhash)


def _simhash_bands(simhash: int) -> tuple[int, int, int, int]:
    mask = (1 << 16) - 1
    return tuple(((band << 16) | ((simhash >> (band * 16)) & mask)) for band in range(4))


def _load_existing_rows(
    output_jsonl: Path,
    seen_hashes: set[str],
    near_duplicate_index: dict[int, list[int]],
    config: MaterializationConfig,
) -> dict[str, Any]:
    if not output_jsonl.exists():
        return _empty_metrics()
    counters = _Counters.from_existing(_empty_metrics())
    with output_jsonl.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            seen_hashes.add(str(row["text_sha256"]))
            if "near_duplicate_simhash64" not in row:
                simhash = _simhash64(_normalize_text(str(row["text"])))
                row["near_duplicate_simhash64"] = f"{simhash:016x}"
            _add_near_duplicate_hash(
                row,
                near_duplicate_index,
                config,
            )
            counters.accept(row)
    return {
        "rows_seen": counters.rows_accepted,
        "rows_accepted": counters.rows_accepted,
        "tokens": counters.split_tokens,
        "split_counts": counters.split_counts,
        "dataset_config_counts": counters.dataset_config_counts,
        "languages": counters.languages,
        "licenses": counters.licenses,
        "config_split_tokens": counters.config_split_tokens,
        "temporal_split_counts": counters.temporal_split_counts,
        "temporal_split_tokens": counters.temporal_split_tokens,
        "content_role_counts": counters.content_role_counts,
        "content_role_tokens": counters.content_role_tokens,
        "timestamp_coverage": {
            "rows_with_timestamp": counters.rows_with_timestamp,
            "rows_without_timestamp": counters.rows_without_timestamp,
        },
        "excluded_reasons": {},
    }


def _empty_metrics() -> dict[str, Any]:
    return {
        "rows_seen": 0,
        "rows_accepted": 0,
        "tokens": {},
        "split_counts": {},
        "dataset_config_counts": {},
        "config_split_tokens": {},
        "temporal_split_counts": {},
        "temporal_split_tokens": {},
        "content_role_counts": {},
        "content_role_tokens": {},
        "timestamp_coverage": {},
        "languages": {},
        "licenses": {},
        "excluded_reasons": {},
    }


def _ratio(numerator: int, denominator: int) -> float:
    return float(numerator / denominator) if denominator else 0.0


def _file_sha256(path: Path) -> str:
    if not path.exists():
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()
