from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from weightlab.hf_corpus import DATASET_COLUMN_ALIASES

SECRET_PATTERNS = [
    re.compile(r"ghp_[A-Za-z0-9_]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (?:RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][^'\"]{12,}['\"]"),
    re.compile(r"(?i)authorization:\s*bearer\s+[A-Za-z0-9._\-]{16,}"),
]

PATH_EXCLUDES = (
    ".git/",
    "__pycache__/",
    "build/",
    "dist/",
    "node_modules/",
    "site-packages/",
    "third_party/",
    "vendor/",
)

GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated by",
    "this file was generated",
)

MALICIOUS_INSTRUCTION_MARKERS = (
    "ignore previous instructions",
    "ignore all previous instructions",
    "reveal your system prompt",
    "developer message",
    "system prompt",
    "prompt injection",
)

CONTAMINATION_PATH_MARKERS = (
    "/benchmark/",
    "/benchmarks/",
    "/eval/",
    "/evals/",
    "/evaluation/",
    "/evaluations/",
    "humaneval",
    "mbpp",
)


@dataclass(frozen=True)
class MaterializationConfig:
    target_train_tokens: int = 50_000_000
    max_train_tokens_per_config: int | None = None
    max_row_bytes: int = 256_000
    min_row_bytes: int = 20
    max_rows: int | None = None
    corpus_use: str = "exploratory-research-only"


RowFactory = Callable[[dict[str, Any], dict[str, Any]], Iterable[dict[str, Any]]]


def materialize_hf_corpus(
    hf_manifest_record: dict[str, Any],
    *,
    output_jsonl: Path,
    row_factory: RowFactory,
    config: MaterializationConfig | None = None,
    resume: bool = True,
) -> dict[str, Any]:
    config = config or MaterializationConfig()
    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    seen_hashes: set[str] = set()
    existing_metrics = (
        _load_existing_rows(output_jsonl, seen_hashes) if resume else _empty_metrics()
    )
    mode = "a" if resume and output_jsonl.exists() else "w"

    source_manifest_metrics = hf_manifest_record["metrics"]
    dataset_revisions = {
        source["dataset"]: source["resolved_revision"]
        for source in source_manifest_metrics["sources"]
    }
    counters = _Counters.from_existing(existing_metrics)
    excluded_examples: list[dict[str, str]] = []

    with output_jsonl.open(mode, encoding="utf-8") as handle:
        for source in source_manifest_metrics["sources"]:
            for accepted_config in source["accepted_configs"]:
                if _target_met(counters, config):
                    break
                config_key = _config_key(source, accepted_config)
                if _config_train_cap_met(counters, config, config_key):
                    continue
                rows = row_factory(source, accepted_config)
                for raw_row in rows:
                    if _target_met(counters, config):
                        break
                    if _config_train_cap_met(counters, config, config_key):
                        break
                    counters.rows_seen += 1
                    candidate = _row_to_candidate(
                        source,
                        accepted_config,
                        raw_row,
                        corpus_use=config.corpus_use,
                    )
                    reason = _rejection_reason(candidate, seen_hashes, config)
                    if reason:
                        counters.excluded_reasons[reason] += 1
                        if len(excluded_examples) < 50:
                            excluded_examples.append(
                                {
                                    "dataset": candidate["dataset"],
                                    "config": candidate["config"],
                                    "repo": candidate["repo"],
                                    "path": candidate["path"],
                                    "reason": reason,
                                }
                            )
                        continue
                    seen_hashes.add(candidate["text_sha256"])
                    handle.write(json.dumps(candidate, sort_keys=True) + "\n")
                    counters.accept(candidate)
                if _target_met(counters, config):
                    break

    checksum = _file_sha256(output_jsonl)
    status = (
        "completed"
        if counters.split_tokens["train"] >= config.target_train_tokens
        else "insufficient_tokens"
    )
    return {
        "benchmark_label": "hf_corpus_materialization",
        "status": status,
        "corpus_use": config.corpus_use,
        "production_approval": False,
        "redistribution_approval": False,
        "source_manifest": {
            "experiment_id": hf_manifest_record["experiment_id"],
            "git_commit": hf_manifest_record["git_commit"],
            "manifest_sha256": source_manifest_metrics["manifest_sha256"],
            "dataset_revisions": dataset_revisions,
        },
        "output": {
            "jsonl_path": str(output_jsonl),
            "bytes": output_jsonl.stat().st_size if output_jsonl.exists() else 0,
            "sha256": checksum,
        },
        "target_train_tokens": config.target_train_tokens,
        "max_train_tokens_per_config": config.max_train_tokens_per_config,
        "meets_50m_token_requirement": counters.split_tokens["train"] >= 50_000_000,
        "rows_seen": counters.rows_seen,
        "rows_accepted": counters.rows_accepted,
        "rows_excluded": sum(counters.excluded_reasons.values()),
        "excluded_reasons": dict(sorted(counters.excluded_reasons.items())),
        "excluded_examples": excluded_examples,
        "tokens": dict(sorted(counters.split_tokens.items())),
        "total_tokens": sum(counters.split_tokens.values()),
        "document_count": counters.rows_accepted,
        "split_counts": dict(sorted(counters.split_counts.items())),
        "config_split_tokens": dict(sorted(counters.config_split_tokens.items())),
        "dataset_config_counts": dict(sorted(counters.dataset_config_counts.items())),
        "languages": dict(sorted(counters.languages.items())),
        "licenses": dict(sorted(counters.licenses.items())),
        "transformations": [
            "extract text/repo/path/language/license columns from Dataset Viewer parquet rows",
            "reject binary/corrupt/unusable rows",
            "reject technical secret/confidential patterns",
            "reject generated/vendor dependency paths",
            "reject exact duplicate normalized text",
            "reject known evaluation-contamination path markers",
            "reject malicious embedded instruction markers",
            "assign repository-aware train/validation/test split by stable repo hash",
            "count byte-tokenizer tokens as utf8 bytes plus eos",
            "optionally cap accepted train tokens per dataset/config before moving on",
            "write jsonl rows with source dataset/config/revision and row checksums",
        ],
        "filters": {
            "max_row_bytes": config.max_row_bytes,
            "min_row_bytes": config.min_row_bytes,
            "path_excludes": list(PATH_EXCLUDES),
            "contamination_path_markers": list(CONTAMINATION_PATH_MARKERS),
            "generated_markers": list(GENERATED_MARKERS),
            "malicious_instruction_markers": list(MALICIOUS_INSTRUCTION_MARKERS),
        },
        "limitations": [
            "exploratory_research_only_not_production_approved",
            "mixed_or_unclear_license_metadata_not_blocking_exploratory_training",
            "near_duplicate_filter_pending",
            "no_functional_training_run_from_this_mirror_yet",
        ],
    }


def load_jsonl_texts(
    path: Path,
    max_documents: int | None = None,
    *,
    split: str | None = None,
) -> list[str]:
    texts: list[str] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            if split is not None and row.get("split") != split:
                continue
            texts.append(str(row["text"]))
            if max_documents is not None and len(texts) >= max_documents:
                break
    return texts


@dataclass
class _Counters:
    rows_seen: int
    rows_accepted: int
    split_tokens: Counter[str]
    split_counts: Counter[str]
    dataset_config_counts: Counter[str]
    config_split_tokens: Counter[str]
    languages: Counter[str]
    licenses: Counter[str]
    excluded_reasons: Counter[str]

    @classmethod
    def from_existing(cls, metrics: dict[str, Any]) -> _Counters:
        return cls(
            rows_seen=int(metrics.get("rows_seen", 0)),
            rows_accepted=int(metrics.get("rows_accepted", 0)),
            split_tokens=Counter(metrics.get("tokens", {})),
            split_counts=Counter(metrics.get("split_counts", {})),
            dataset_config_counts=Counter(metrics.get("dataset_config_counts", {})),
            config_split_tokens=Counter(metrics.get("config_split_tokens", {})),
            languages=Counter(metrics.get("languages", {})),
            licenses=Counter(metrics.get("licenses", {})),
            excluded_reasons=Counter(metrics.get("excluded_reasons", {})),
        )

    def accept(self, row: dict[str, Any]) -> None:
        split = str(row["split"])
        self.rows_accepted += 1
        self.split_tokens[split] += int(row["tokens"])
        self.split_counts[split] += 1
        config_key = f"{row['dataset']}::{row['config']}"
        self.dataset_config_counts[config_key] += 1
        self.config_split_tokens[f"{config_key}::{split}"] += int(row["tokens"])
        self.languages[str(row["language"])] += 1
        self.licenses[str(row["license"])] += 1


def _row_to_candidate(
    source: dict[str, Any],
    accepted_config: dict[str, Any],
    raw_row: dict[str, Any],
    *,
    corpus_use: str,
) -> dict[str, Any]:
    text = _first_value(raw_row, DATASET_COLUMN_ALIASES["text"])
    repo = _first_value(raw_row, DATASET_COLUMN_ALIASES["repo"])
    path = _first_value(raw_row, DATASET_COLUMN_ALIASES["path"])
    language = _first_value(raw_row, DATASET_COLUMN_ALIASES["language"]) or accepted_config[
        "language"
    ]
    license_name = _first_value(raw_row, DATASET_COLUMN_ALIASES["license"]) or accepted_config[
        "license"
    ]
    normalized = _normalize_text(text)
    text_sha256 = hashlib.sha256(normalized.encode("utf-8", errors="ignore")).hexdigest()
    split = _repo_split(repo)
    return {
        "dataset": source["dataset"],
        "config": accepted_config["config"],
        "dataset_revision": source["resolved_revision"],
        "source_manifest_sha256": source.get("manifest_sha256", ""),
        "split": split,
        "repo": repo,
        "path": path,
        "language": language,
        "license": license_name,
        "license_metadata_status": accepted_config.get("license_metadata_status", ""),
        "corpus_use": corpus_use,
        "text": text,
        "tokens": _byte_tokens(text),
        "bytes": len(text.encode("utf-8", errors="ignore")),
        "text_sha256": text_sha256,
        "row_sha256": hashlib.sha256(
            json.dumps(
                {
                    "dataset": source["dataset"],
                    "config": accepted_config["config"],
                    "repo": repo,
                    "path": path,
                    "text_sha256": text_sha256,
                },
                sort_keys=True,
            ).encode("utf-8")
        ).hexdigest(),
    }


def _rejection_reason(
    row: dict[str, Any],
    seen_hashes: set[str],
    config: MaterializationConfig,
) -> str:
    text = row["text"]
    path = f"/{str(row['path']).lower()}"
    lowered_text_head = text[:4096].lower()
    if not text or not str(text).strip():
        return "empty_text"
    if len(text.encode("utf-8", errors="ignore")) < config.min_row_bytes:
        return "too_small"
    if row["bytes"] > config.max_row_bytes:
        return "too_large"
    if "\x00" in text:
        return "binary_or_corrupt"
    if row["text_sha256"] in seen_hashes:
        return "duplicate_text"
    if any(marker in path for marker in PATH_EXCLUDES) or path.endswith(".min.js"):
        return "vendor_or_generated_path"
    if any(marker in path for marker in CONTAMINATION_PATH_MARKERS):
        return "evaluation_contamination_path"
    if any(marker in lowered_text_head for marker in GENERATED_MARKERS):
        return "generated_marker"
    if any(pattern.search(text) for pattern in SECRET_PATTERNS):
        return "secret_or_confidential_pattern"
    if any(marker in lowered_text_head for marker in MALICIOUS_INSTRUCTION_MARKERS):
        return "malicious_embedded_instruction"
    return ""


def _target_met(counters: _Counters, config: MaterializationConfig) -> bool:
    if counters.split_tokens["train"] >= config.target_train_tokens:
        return True
    return config.max_rows is not None and counters.rows_accepted >= config.max_rows


def _config_train_cap_met(
    counters: _Counters,
    config: MaterializationConfig,
    config_key: str,
) -> bool:
    if config.max_train_tokens_per_config is None:
        return False
    return (
        counters.config_split_tokens[f"{config_key}::train"]
        >= config.max_train_tokens_per_config
    )


def _config_key(source: dict[str, Any], accepted_config: dict[str, Any]) -> str:
    return f"{source['dataset']}::{accepted_config['config']}"


def _first_value(row: dict[str, Any], names: list[str]) -> str:
    for name in names:
        value = row.get(name)
        if value is not None:
            return str(value)
    return ""


def _normalize_text(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.strip().splitlines())


def _byte_tokens(text: str) -> int:
    return len(text.encode("utf-8", errors="ignore")) + 1


def _repo_split(repo: str) -> str:
    digest = hashlib.sha256(repo.encode("utf-8", errors="ignore")).digest()
    bucket = int.from_bytes(digest[:2], "big") % 100
    if bucket < 2:
        return "test"
    if bucket < 5:
        return "validation"
    return "train"


def _load_existing_rows(output_jsonl: Path, seen_hashes: set[str]) -> dict[str, Any]:
    if not output_jsonl.exists():
        return _empty_metrics()
    counters = _Counters.from_existing(_empty_metrics())
    with output_jsonl.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            seen_hashes.add(str(row["text_sha256"]))
            counters.accept(row)
    return {
        "rows_seen": counters.rows_accepted,
        "rows_accepted": counters.rows_accepted,
        "tokens": counters.split_tokens,
        "split_counts": counters.split_counts,
        "dataset_config_counts": counters.dataset_config_counts,
        "languages": counters.languages,
        "licenses": counters.licenses,
        "excluded_reasons": {},
    }


def _empty_metrics() -> dict[str, Any]:
    return {
        "rows_seen": 0,
        "rows_accepted": 0,
        "tokens": {},
        "split_counts": {},
        "dataset_config_counts": {},
        "config_split_tokens": {},
        "languages": {},
        "licenses": {},
        "excluded_reasons": {},
    }


def _file_sha256(path: Path) -> str:
    if not path.exists():
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()
